# Generated by Django 4.1.7 on 2023-03-23 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0002_remove_class_room_student_class_room_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('room_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_Age',
            new_name='student_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_Code',
            new_name='student_code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_Name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacher_Age',
            new_name='teacher_age',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacher_Code',
            new_name='teacher_code',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacher_Name',
            new_name='teacher_name',
        ),
        migrations.DeleteModel(
            name='Class_Room',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_room.teacher'),
        ),
    ]
