# Generated by Django 4.1.7 on 2023-03-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0003_classroom_rename_student_age_student_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
